"""
Agent Route — Autonomous Bias Audit

Endpoints:
- POST /api/agent/audit     — Start an autonomous audit
- GET  /api/agent/{id}      — Get audit status and trace
- GET  /api/agent/{id}/report — Download the generated PDF report
"""

import uuid
import io
from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional

from app.services.agent import run_audit_agent, get_session

router = APIRouter(prefix="/api/agent", tags=["AI Agent"])


class AuditRequest(BaseModel):
    dataset_id: str
    instruction: str
    protected_attributes: Optional[list[str]] = None
    label_column: Optional[str] = ""
    favorable_label: Optional[str | int | float] = ""


class TraceStepResponse(BaseModel):
    step_type: str
    content: str
    tool_name: Optional[str] = None
    tool_args: Optional[dict] = None
    tool_result_summary: Optional[str] = None


class AuditResponse(BaseModel):
    session_id: str
    status: str
    trace: list[TraceStepResponse]
    final_narrative: str
    has_report: bool
    has_inspect_data: bool
    has_measure_data: bool
    has_flag_data: bool
    has_fix_data: bool
    inspect_data: Optional[dict] = None
    measure_data: Optional[dict] = None
    flag_data: Optional[dict] = None
    fix_data: Optional[dict] = None


@router.post("/audit", response_model=AuditResponse)
async def start_audit(request: AuditRequest):
    """
    Start an autonomous bias audit.

    The agent will:
    1. Profile the dataset
    2. Compute fairness metrics
    3. Flag bias issues and check compliance
    4. Apply mitigation techniques
    5. Generate a PDF report

    All steps are autonomous — the agent decides the order
    and adapts based on what it finds.
    """
    session_id = f"audit_{uuid.uuid4().hex[:8]}"

    # Strip inputs
    label_col = request.label_column.strip() if request.label_column else ""
    fav_label = str(request.favorable_label).strip() if request.favorable_label else ""
    attrs = [a.strip() for a in request.protected_attributes] if request.protected_attributes else []

    session = await run_audit_agent(
        session_id=session_id,
        dataset_id=request.dataset_id,
        user_instruction=request.instruction,
        protected_attributes=attrs,
        label_column=label_col,
        favorable_label=fav_label,
    )

    return AuditResponse(
        session_id=session_id,
        status=session.status,
        trace=[
            TraceStepResponse(
                step_type=t.step_type,
                content=t.content,
                tool_name=t.tool_name,
                tool_args=t.tool_args,
                tool_result_summary=t.tool_result_summary,
            )
            for t in session.trace
        ],
        final_narrative=session.final_narrative,
        has_report=session.report_bytes is not None,
        has_inspect_data=session.inspect_data is not None,
        has_measure_data=session.measure_data is not None,
        has_flag_data=session.flag_data is not None,
        has_fix_data=session.fix_data is not None,
        inspect_data=session.inspect_data,
        measure_data=session.measure_data,
        flag_data=session.flag_data,
        fix_data=session.fix_data,
    )


@router.get("/{session_id}", response_model=AuditResponse)
async def get_audit_status(session_id: str):
    """Get the current status and trace of an audit session."""
    session = get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Audit session not found")

    return AuditResponse(
        session_id=session_id,
        status=session.status,
        trace=[
            TraceStepResponse(
                step_type=t.step_type,
                content=t.content,
                tool_name=t.tool_name,
                tool_args=t.tool_args,
                tool_result_summary=t.tool_result_summary,
            )
            for t in session.trace
        ],
        final_narrative=session.final_narrative,
        has_report=session.report_bytes is not None,
        has_inspect_data=session.inspect_data is not None,
        has_measure_data=session.measure_data is not None,
        has_flag_data=session.flag_data is not None,
        has_fix_data=session.fix_data is not None,
        inspect_data=session.inspect_data,
        measure_data=session.measure_data,
        flag_data=session.flag_data,
        fix_data=session.fix_data,
    )


@router.get("/{session_id}/report")
async def download_agent_report(session_id: str):
    """Download the PDF report generated by the agent."""
    session = get_session(session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Audit session not found")

    if not session.report_bytes:
        raise HTTPException(status_code=404, detail="No report generated yet")

    return StreamingResponse(
        io.BytesIO(session.report_bytes),
        media_type="application/pdf",
        headers={
            "Content-Disposition": f'attachment; filename="fairnesslens_agent_audit_{session_id}.pdf"',
        },
    )